version: '3.9'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - REACT_APP_VITE_SERVER_LINK=${REACT_APP_VITE_SERVER_LINK}
        - REACT_APP_VITE_WEB_SOCKET_LINK=${REACT_APP_VITE_WEB_SOCKET_LINK}
    image: milease/camai-backend:camai-web-manager
    ports:
      - 3010:4174
